export enum MttPlayerStatus {
  WAITING_APPLY= 0,
  CAN_APPLY_NOT_START= 1,
  CAN_APPLY_DELAY= 2,
  APPLIED_NOT_START= 3,
  CAN_JOIN= 4,
  CANNOT_APPLY_STARTED= 5,
  LOSE_CAN_REBUY= 6,
  LOSE= 7,
  JOIN_COMPLETE= 8,
  NOT_JOIN_COMPLETE= 9,
  CANNOT_JOIN_OVERTIME= 10,
}