/**
 * @module DiamondConfigType
 * @description 钻石配置代号
 */
export enum DiamondConfigType {
    NONE = 0,
    /** 创建牌桌 */
    CREATE_TABLE = 1,
    /** 牌桌内加时 */
    ADD_TIME = 2,
    /** 语音桌 */
    AUDIO_TABLE = 3,
    /** 人脸识别桌 */
    FACE_VERIFICATION = 4,
    /** 视频桌（全时长） */
    VIDEO_FULL_TIME = 5,
    /** 视频桌（随机验证） */
    VIDEO_RANDOM = 6,
    /** 视频桌（麦序） */
    VIDEO_SEQUENCE = 7,
    /** 延迟看牌 */
    DELAY_LOOK = 8,
    /** 聊天 */
    CHAT = 10,
    /** 区块链 */
    BLOCKCHAIN = 18,
    /** 麻将 */
    MAHJONG = 19,
    /** 保险 */
    INSURANCE = 22,
    IP = 23,
    GPS = 24,
    /** 暴击 */
    CRIT = 25,
    /** 蘑菇 */
    MUSH = 26,
    /** 鱿鱼 */
    SQUID = 27,
    JACKPOT = 28,
    /** 牛仔 */
    Cowboy = 29,
    /** 看全部公牌 */
    ViewAllPublicCards = 31,
    /** 麻将语音 */
    MahjongAudio = 32,
    /** 麻将视频全时长 */
    MahjongVideoFullTime = 33,
    /** 麻将视频随机验证 */
    MahjongVideoRandom = 34,
    /** 麻将视频麦序 */
    MahjongVideoSequence = 35
}
